name: generic_argument_factory_integration
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation:

dev_dependencies:
  build_runner: ^1.12.0
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0
  freezed:
  test:

dependency_overrides:
  freezed:
    path: ../../freezed
  freezed_annotation:
    path: ../../freezed_annotation
  json_serializable:
    path: ../../../../../json_serializable.dart/json_serializable
  json_annotation:
    path: ../../../../../json_serializable.dart/json_annotation
