name: freezed_workspace

environment:
  sdk: "^3.8.0"

workspace:
  - benchmarks/
  - packages/freezed
  - packages/freezed/example
  - packages/freezed_annotation
  - packages/freezed_lint
  - packages/freezed_lint/example
