include: ../../analysis_options.yaml

analyzer:
  enable-experiment:
    - primary-constructors
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
