targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          exclude:
            - example
            - test/source_gen_src.dart
          include:
            - test/*
            - test/**/*
        options:
          format: true
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: ["freezed"]
    build_extensions: { ".dart": [".freezed.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable|json_serializable"]
