name: _internal
description: A new Flutter project.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner:
  freezed: ^2.4.5
