name: example
description: A new Flutter project.

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  freezed_annotation: ">= 0.11.0"

dev_dependencies:
  build_runner:

dependency_overrides:
  freezed:
    path: ../freezed
  freezed_annotation:
    path: ../freezed_annotation
