name: freezed_benchmarks
description: A new Flutter project.
publish_to: none

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  freezed: ^3.0.2
  json_serializable: ^6.1.3
  build_runner:
