name: Build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

jobs:
  freezed:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - master
          - stable
        dependencies:
          - get
          - downgrade
        exclude:
          - channel: master
            dependencies: downgrade

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          cache: ${{ matrix.channel == 'stable' }}

      - name: Install Melos
        uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: false

      - name: Install dependencies
        run: flutter pub ${{ matrix.dependencies }}

      - name: Check format
        # Check dart format only on master
        if: matrix.channel == 'master'
        run: dart format .

      - name: Generate
        run: melos generate

      - name: Analyze
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: |
          melos exec --flutter -- flutter test
          melos exec --no-flutter -- dart test

      - name: Lint golden test
        run: dart run custom_lint --fatal-infos
        working-directory: "packages/freezed_lint/example"
