targets:
  $default:
    builders:
      freezed:
        options:
          # Disable formatting of generated files, to improve generation performance.
          format: false
          union_key: custom-key
          union_value_case: pascal
          maybe_map: true
          maybe_when: true
